project:
  type: website

website:
  title: "Code Digressions"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/J-yash
      - icon: substack
        href: https://www.subtledigressions.com
format:
  html:
    theme:
      - litera
      - brand
    css: styles.css



